resources/js/components/HomeMap.vue, resources/views/welcome.blade.php
=> feat: homepage texts

resources/js/components/ArtworkCarousel.vue, resources/views/welcome.blade.php
Have to ask gorazd. If these are all the buttons to be styled
=> style: home-page hover preskúmať button

resources/views/welcome.blade.php
Task description:
```
old: Objavujte umenie v uliciach Bratislavy. Cieľom je prezentovať a popularizovať pestrú škálu umenia vo verejnom priestore od 2. polovice 20. storočia až po súčasnosť.
new: [Katarína Buzová](https://jira.sng.sk/secure/ViewProfile.jspa?name=kbuzova) doplní --> doplnené:
NEW: 
Objavujte a chráňte umenie v uliciach Bratislavy.
Databáza dokumentuje a popularizuje pestrú škálu diel vo verejnom priestore od 2. polovice 20. storočia až po súčasnosť.
Ešte jedna vec: namiesto / použiť "zo" pri mestských častiach
```
=> chore: change / to zo in boroughs & change welcome text

resources/js/components/ArtworkCarousel.vue, resources/js/components/DistrictWrapper.vue, resources/js/components/search/MobileFilter.vue, resources/js/components/search/MobileFilterDialog.vue, resources/views/about.blade.php, resources/views/artworks/index.blade.php, resources/views/artworks/show.blade.php, resources/views/components/artwork-card.blade.php, resources/views/components/category-with-icon.blade.php, resources/views/layouts/app.blade.php, resources/views/welcome.blade.php
=> style: replace md with lg

resources/views/welcome.blade.php
=> Gmbuvp 50: Viac diel

resources/js/components/ArtworkCarousel.vue
Will wait for Gorazd approval, assign to review later
=> style: artwork in carousel

resources/css/fonts.css, resources/js/components/search/MobileFilterDialog.vue, resources/js/components/search/PopoverFilter.vue, resources/views/artworks/index.blade.php, resources/views/layouts/app.blade.php, tailwind.config.js
Did not get variable font, yet
=> feat: add animation + fixed header

resources/views/artworks/show.blade.php, resources/views/welcome.blade.php
Outdated: Need gorazd approval
=> feat: add viac do katalogu na mobil + styler

resources/js/components/ArtworksMasonry.vue, resources/js/components/MapContainer.vue, resources/js/components/search/Map.vue, resources/views/artworks/index.blade.php
https://github.com/SlovakNationalGallery/umenie-mesta-bratislavy/assets/28804184/a759f208-a2a0-4077-a8ca-516a72b6368b
=> feat: zmenšiť/zvačšiť na desktope

app/Jobs/ImportFromAirtable.php, app/Models/Artwork.php, database/migrations/2023_06_29_151653_add_photo_source.php, resources/js/components/ArtworkCarousel.vue
=> feat: add source to photos

resources/views/artworks/index.blade.php
=> style: borough items

resources/views/artworks/index.blade.php
=> style: selection

resources/css/app.css, resources/img/locate.svg, resources/img/minus.svg, resources/img/plus.svg, resources/js/components/search/Map.vue
=> style: map buttons

resources/views/artworks/index.blade.php
=> feat: add removeAllSelection on desktop

resources/css/app.css, resources/js/components/ArtworkCarousel.vue
Make it scrollable and swipeable
=> feat: create carousel

resources/js/components/search/FiltersController.vue, resources/js/components/search/MobileFilterDialog.vue, resources/views/artworks/index.blade.php
=> feat: add show more

resources/js/components/MapContainer.vue
=> Center map cluster labels

app/Jobs/ImportFromAirtable.php, database/migrations/2023_07_13_140047_add_artworks_promoted.php, routes/web.php
feat: add promoted column
feat: promote promoted artworks on homepage
=> Feat: promote artworks on homepage

resources/js/components/MapContainer.vue
=> feat: add map localisation

app/Jobs/ImportFromAirtable.php
To account for re-used Airtable attachment IDs among Photos
=> Improve Media clean-up logic

resources/views/about.blade.php
Check with figma:
https://www.figma.com/file/yXGnVwrdPOG7aGvuSfgeir/GMB-design?type=design&node-id=546-288&mode=design&t=yDxMYbGjEaHTh4Wr-0
=> feat: new about page texts

.prettierrc.json, package-lock.json, package.json, resources/views/artworks/show.blade.php
https://jira.sng.sk/browse/GMBUVP-120
=> fix: shrinking icon

resources/js/components/MapContainer.vue
https://jira.sng.sk/browse/GMBUVP-130
=> fix: max zoom in artworks listing

.gitignore, resources/views/artworks/index.blade.php
fix: keywords mobile filter
chore: ignore DS_Store
=> GMBUVP-118: Keyword filter on small screens

app/Models/Artwork.php, database/factories/ArtworkFactory.php, database/factories/LocationFactory.php, tests/Feature/ArtworkTest.php
https://jira.sng.sk/browse/GMBUVP-147
=> Fix discrepancy of artworks count in locations

resources/js/components/MapContainer.vue
https://jira.sng.sk/browse/GMBUVP-137
=> GMBUVP-137: Force translate geolocate control label
